name: publish modules

on:
  push:
    branches:
      - main
    paths:
      - '**/package.json'
  workflow_dispatch:

jobs:
  list-modules:
    name: list modules
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.result.outputs.modules }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm pkg get '' --workspaces | jq -c keys | tee modules.json
      - run: echo "::set-output name=modules::$(cat modules.json)"
        id: result
  publish-module:
    name: publish module
    runs-on: ubuntu-latest
    needs:
      - list-modules
    permissions:
      contents: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.list-modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
        # cache: npm
      - run: |
          cat <<'EOB' > .npmrc
          @sasaplus1-prototype:https://npm.pkg.github.com/
          //npm.pkg.github.com/:_authToken=${NPM_TOKEN}
          EOB
      - id: previous-version
        run: echo "::set-output name=value::$(npm info '${{ matrix.module }}' version)"
        continue-on-error: true
      - run: npm publish --workspace '${{ matrix.module }}'
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: publish
        continue-on-error: true
      - id: rev-range
        run: |
          if [ -z '${{ steps.previous-version.outputs.value }}' ]
          then
            echo "::set-output name=range::$(git rev-list --max-parents=0 HEAD)..HEAD"
          else
            echo "::set-output name=range::${{ matrix.module }}@${{ steps.previous-version.outputs.value }}..HEAD"
          fi
      - run: >
          npm pkg get repository.directory --workspace '${{ matrix.module }}' |
          jq -r 'to_entries | .[].value' |
          tee dir.txt
      - run: >
          git log --format='- %h @%an `%s`' '${{ steps.rev-range.outputs.range }}' -- "$(cat dir.txt)" | tee changelog.md
      - run: >
          npm pkg get version --workspace '${{ matrix.module }}' |
          jq -r 'to_entries | .[].value' |
          tee version.txt
      - id: version
        run: echo "::set-output name=value::$(cat version.txt)"
      - run: gh release create '${{ matrix.module }}@${{ steps.version.outputs.value }}' -F changelog.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.publish.outcome == 'success'
