name: publish modules

on:
  push:
    paths:
      - '**/package.json'
  workflow_dispatch:

jobs:
  list-modules:
    name: list modules
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.result.outputs.modules }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm pkg get '' --workspaces | jq -c keys
      - run: echo "::set-output name=modules::$(cat modules.json)"
        id: result
  publish-module:
    name: publish module
    runs-on: ubuntu-latest
    needs:
      - list-modules
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.list-modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: |
          cat <<'EOB' > .npmrc
          @sasaplus1-prototype:https://npm.pkg.github.com/
          //npm.pkg.github.com/:_authToken=${NPM_TOKEN}
          EOB
      - run: npm publish --workspace ${{ matrix.module }}
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
